name: Run Cypress tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx start-server-and-test 'npm run dev' http://localhost:3000 'npx cypress run --browser chrome'
